[core]
reloadable = true
order = 0

[package]
version = "0.0.2"
category = "Simulation"
title = "ROS Bridge (add-on)"
description = "ROS interfaces used for add-ons"
authors = ["Toni-SM"]
repository = ""
keywords = ["ROS"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"

[dependencies]
"omni.kit.uiapp" = {}
"omni.isaac.ros_bridge" = {}
"omni.usd.schema.add_on" = {}
"omni.add_on.ros_bridge_ui" = {}
"omni.kit.pip_archive" = {} # pulls in numpy and opencv

[[python.module]]
name = "omni.add_on.ros_bridge"

[[python.module]]
name = "omni.add_on.ros_bridge.tests"

[settings]
exts."omni.add_on.ros_bridge".nodeName = "OmniAddOnRosBridge"
